"""add_loan_table

Revision ID: 420e63152b0e
Revises: aa763b2822a0
Create Date: 2026-01-12 16:42:07.222218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '420e63152b0e'
down_revision: Union[str, Sequence[str], None] = 'aa763b2822a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loans',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('book_copy_id', sa.UUID(), nullable=False),
    sa.Column('loaned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fine_amount_final', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('renewals_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_copy_id'], ['book_copies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_loans_book_copy_id', 'loans', ['book_copy_id'], unique=False)
    op.create_index('ix_loans_due_date', 'loans', ['due_date'], unique=False)
    op.create_index('ix_loans_overdue', 'loans', ['due_date', 'returned_at'], unique=False)
    op.create_index('ix_loans_returned_at', 'loans', ['returned_at'], unique=False)
    op.create_index('ix_loans_user_active', 'loans', ['user_id', 'returned_at'], unique=False)
    op.create_index('ix_loans_user_id', 'loans', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_loans_user_id', table_name='loans')
    op.drop_index('ix_loans_user_active', table_name='loans')
    op.drop_index('ix_loans_returned_at', table_name='loans')
    op.drop_index('ix_loans_overdue', table_name='loans')
    op.drop_index('ix_loans_due_date', table_name='loans')
    op.drop_index('ix_loans_book_copy_id', table_name='loans')
    op.drop_table('loans')
    # ### end Alembic commands ###
