"""add_reservation_table

Revision ID: bc96d9edf06f
Revises: 420e63152b0e
Create Date: 2026-01-12 22:00:20.935015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc96d9edf06f'
down_revision: Union[str, Sequence[str], None] = '420e63152b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('book_title_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ON_HOLD', 'FULFILLED', 'EXPIRED', 'CANCELLED', name='reservation_status'), nullable=False),
    sa.Column('hold_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_title_id'], ['book_titles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reservations_book_title_id', 'reservations', ['book_title_id'], unique=False)
    op.create_index('ix_reservations_hold_expires', 'reservations', ['status', 'hold_expires_at'], unique=False)
    op.create_index('ix_reservations_status', 'reservations', ['status'], unique=False)
    op.create_index('ix_reservations_title_active', 'reservations', ['book_title_id', 'status', 'created_at'], unique=False)
    op.create_index('ix_reservations_user_id', 'reservations', ['user_id'], unique=False)
    op.create_index('ix_reservations_user_title_active', 'reservations', ['user_id', 'book_title_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reservations_user_title_active', table_name='reservations')
    op.drop_index('ix_reservations_user_id', table_name='reservations')
    op.drop_index('ix_reservations_title_active', table_name='reservations')
    op.drop_index('ix_reservations_status', table_name='reservations')
    op.drop_index('ix_reservations_hold_expires', table_name='reservations')
    op.drop_index('ix_reservations_book_title_id', table_name='reservations')
    op.drop_table('reservations')
    # Drop the enum type
    op.execute("DROP TYPE IF EXISTS reservation_status")
    # ### end Alembic commands ###
